objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <displayFormat>book-{0000}</displayFormat>
        <label>Book No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BAexam.cls
global class BAexam implements Database.Batchable<Book__c>{

            global Iterable<Book__c> start(Database.BatchableContext bc){
            List<Book__c> blist =new List<Book__c>();
            blist=[select id,Name,Title__c,Author__c,Price__c from Book__c];
            return blist; 

}

            global void execute(Database.BatchableContext bc, LIST<Book__c> blist){
            
            for(Book__c b1:blist){
            b1.price__C=0;
            update b1;
            
            }  
            
            }  
            
            global void finish(Database.BatchableContext bc){
            
            
            }     
            
           


}