objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Edition__c</fullName>
        <label>Edition</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <displayFormat>book-{0000}</displayFormat>
        <label>Book No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ColletionTest2.cls
public class ColletionTest2{
       public static testMethod void main(){
       List<Rectangle> r1=new List<Rectangle>();
       Book__c book=new Book__c();
       List<Book__c> b1=new List<Book__c>();
       b1.add(book);
       
       book.Title__c = 'cloud computing';
       book.Author__c='arun sepuri';
       book.Edition__c=3.0;
       book.price__c=545;
       insert b1;
       List<book__c> return_books = [select Title__c,Author__c,Price__c,Edition__c from book__c limit 1];
       for (book__c b2: return_books){
       system.debug('returned books' + return_books);       
       }
       
       }
       
}