objects/Mileage__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Miles__c</fullName>
        <label>Miles</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Mileage</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>Mileage Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mileages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/createMemberInbound.cls
global class createMemberInbound implements Messaging.InboundEmailHandler 
{
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email, Messaging.InboundEnvelope env)
    {
    
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
          
        String myPlainText= '';     
            
        myPlainText = email.plainTextBody;  
        
        List<Mileage__c> memb = new List<Mileage__c>();
            
        try 
        {
            Mileage__c mem = new Mileage__c(Miles__c= 4);
            
            memb.add(mem);
            
            insert memb;    
             
            System.debug('New member: ' + memb);   
        } 
            
        catch (Exception e) 
        {
            System.debug('Error is: ' + e);
        }   
          
        result.success = true;
         
        return result;
    }
}