objects/Position__c.object
<CustomObject>
    <description>This object stores the information about the open job positions at our comapny</description>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/shipment__c.object
<CustomObject>
    <fields>
        <fullName>supplier_number__c</fullName>
        <label>supplier number</label>
        <referenceTo>supplier__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>shipment</label>
    <nameField>
        <displayFormat>S-{00}</displayFormat>
        <label>shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestLKP.cls
Public Class TestLKP{

Public Contact con{get;set;}
Public Position__c pos{get;set;}
Public shipment__c shp{get;set;}
String Id;

Public TestLKP (ApexPages.StandardController controller){
con=new Contact();
pos=new Position__c();
shp=new shipment__c();
System.debug('>>>>>>>>HIRE'+Pos.Hiring_Manager__c);
System.debug('>>>>>>>>Shipment'+shp.supplier_number__c);


}
public void act(){

System.debug('>>>>>>>>HIRE'+Pos.Hiring_Manager__c);
System.debug('>>>>>>>>Shipment'+shp.supplier_number__c);



}
}